from __future__ import annotations

from typing import Protocol

from todo.domain.entities import TodoItem


class ITodoRepository(Protocol):
    def get_all(self, completed: bool | None = None) -> list[TodoItem]: ...
    def get_by_id(self, id: str) -> TodoItem | None: ...
    def add(self, item: TodoItem) -> TodoItem: ...
    def update(self, item: TodoItem) -> TodoItem: ...
    def delete(self, id: str) -> bool: ...
